baseURL = "https://sayurua.github.io/"
languageCode = "en-us"
title = "Sayuru Amugoda"
theme = "re-terminal"

[params]
  customCSS = ["css/custom.css"]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  Copyright = "Â© 2025 Sayuru Amugoda"

[languages]
  [languages.en]
    languageName = "English"
    title = "Your Name"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "bio"
        name = "Bio"
        url = "/bio/"
      [[languages.en.menu.main]]
        identifier = "experience"
        name = "Experience"
        url = "/experience/"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
