baseURL = "https://sayurua.github.io/"
languageCode = "en-us"
title = "Sayuru Amugoda"
theme = "re-terminal"

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Your Name"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
